title: "FilosofIA"
description: Wiki colaborativa sobre IA generativa en educación y filosofía
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-include-cache

# Navegación
logo: false
search_enabled: true

url: "https://a-lfre-do.github.io"
baseurl: "/Filosof-IA"

aux_links:
  "Repositorio en GitHub":
    - "https://github.com/a-lfre-do/Filosof-IA"

# Build/Markdown settings (safe for Jekyll 3.10)
markdown: kramdown
kramdown:
  input: GFM

footer_content: "Hecho con ❤️ por docentes y estudiantes. Licencia CC BY-SA 4.0."

footer_logos:
  - image: assets/images/logo-1.png
    alt: "Blasón Universidad de Chile"
    width: 120px
  - image: assets/images/logo-2.png
    alt: "Facultad de Filosofía y Humanidades, Universidad de Chile"
    width: 120px
