title: "FilosofIA"
description: Wiki colaborativa sobre IA generativa en educación y filosofía
remote_theme: just-the-docs/just-the-docs
just_the_docs:
  custom_css: assets/css/custom.scss
  
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-include-cache

# Navegación
logo: /assets/images/Desafio-Filosof-IA.png
logo_alt: "FilosofIA"
search_enabled: true

url: "https://a-lfre-do.github.io"
baseurl: "/Filosof-IA"

aux_links:
  "Repositorio en GitHub":
    - "https://github.com/a-lfre-do/Filosof-IA"

# Build/Markdown settings (safe for Jekyll 3.10)
markdown: kramdown
kramdown:
  input: GFM

footer_content: >
  <p style="margin-bottom: 0.5em;">
    Hecho con ❤️ por docentes y estudiantes. Licencia CC BY-SA 4.0.
  </p></br>
  <div style="display:flex;justify-content:space-between;align-items:center;max-width:400px;margin:0 auto;">
    <img src="/Filosof-IA/assets/images/logo-1.png" alt="Blasón Universidad de Chile" style="width:120px;">
    <img src="/Filosof-IA/assets/images/logo-2.png" alt="Facultad de Filosofía y Humanidades, Universidad de Chile" style="width:120px;">
  </div>
