title: FilosofIA
description: Wiki colaborativa sobre IA generativa en educación y filosofía
theme: just-the-docs

# Base para GitHub Pages
baseurl: "/docs" 
url: "https://Filosof-IA.github.io"  

# Navegación
aux_links:
  "Repositorio en GitHub":
    - "https://github.com/a-lfre-do/Filosof-IA.github.io"

# Footer
footer_content: "Hecho con ❤️ por docentes y estudiantes. Licencia CC BY-SA 4.0."
